views:
  telnetConnected:
    art: _connected.ans

  sshConnected:
    art: _connected.ans
    next:
      menu: authWelcome
      delay: 1000
#    next: authWelcome
#    next:
#    - menu: authSshSecondFactor # require 2FA
#      acs: AR2
#    - menu: demo # this drops a user into the demo menu
#      acs: GM[demo]
#    - menu: authWelcome

  authWelcome:
    art: _welcome.ans